import { CursorEvent } from '@/lib/types'

// REPLACE: Replace all sample events, locations, and Luma URLs with real community events.
export const events: CursorEvent[] = [
  {
    id: 'cafe-cursor-belgrade-summer-2026',
    title: 'Cafe Cursor Belgrade — Summer Edition',
    date: '2026-06-28',
    time: '11:00',
    displayDate: 'June 28, 2026',
    attendees: 67,
    location: 'Belgrade, Serbia',
    recapPath: '/recaps/cafe-cursor-belgrade-summer-2026',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1YmPZwDDF1Op1bSvQ4R3Lx4otJkjlCVUj',
    lumaUrl: 'https://luma.com/cursor-belgrade',
    status: 'past',
  },
  {
    id: 'cursor-meetup-novisad-may-2026',
    title: 'Cursor Meetup Novi Sad',
    date: '2026-05-26',
    time: '18:00',
    displayDate: 'May 26, 2026',
    attendees: 40,
    location: 'Novi Sad, Vojvodina',
    recapPath: '/recaps/cursor-meetup-novisad-may-2026',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1E0NV4YFLlFD8O72R0DrCqQ6pkjvwTE2k',
    lumaUrl: 'https://luma.com/jn59jzyp',
    status: 'past',
  },
  {
    id: 'cursor-coworking-belgrade-1',
    title: 'Cursor Coworking Day in Belgrade',
    date: '2026-05-15',
    time: '09:00',
    displayDate: 'May 15, 2026',
    attendees: 41,
    location: 'Belgrade, Serbia',
    recapPath: '/recaps/cursor-coworking-belgrade-1',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1BlbLo_xRyF3wGcuywTb5-uzqwh7Ona95',
    lumaUrl: 'https://luma.com/9tlvu6ij',
    status: 'past',
  },
  {
    id: 'cursor-meetup-novisad-dec-2025',
    title: 'Cursor Meetup Novi Sad',
    date: '2025-12-23',
    time: '19:30',
    displayDate: 'December 23, 2025',
    attendees: 100,
    location: 'Novi Sad, Vojvodina',
    recapPath: '/recaps/cursor-meetup-novisad-dec-2025',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1mZBieCPcoimNWOv6jgriX_gJJzvc1qKl',
    lumaUrl: 'https://luma.com/udbedo7b',
    status: 'past',
  },
  {
    id: 'cursor-belgrade-hub201-1',
    title: 'Cursor Belgrade Hub201 Meetup',
    date: '2026-04-07',
    time: '17:30',
    displayDate: 'April 7, 2026',
    attendees: 40,
    location: 'Belgrade, Serbia',
    recapPath: '/recaps/cursor-belgrade-hub201-1',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1hdysREWIcVBNH_TdtcqVI04Z_YDQaUyh',
    lumaUrl: 'https://luma.com/yvpg9ijv',
    status: 'past',
  },
  {
    id: 'cafe-cursor-cannes-1',
    title: 'Cafe Cursor Cannes',
    date: '2026-04-02',
    time: '18:00',
    displayDate: 'April 2, 2026',
    attendees: 50,
    location: 'Cannes, Provence-Alpes-Côte d\'Azur',
    recapPath: '/recaps/cafe-cursor-cannes-1',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1yDEyEWC-1WACUkMkRIY_Y5EpkJh0Xkkd',
    lumaUrl: 'https://luma.com/hswzhn5m',
    status: 'past',
  },
  {
    id: 'cursor-meetup-novisad-1',
    title: 'Cursor Meetup Novi Sad',
    date: '2026-03-17',
    time: '18:00',
    displayDate: 'March 17, 2026',
    attendees: 37,
    location: 'Novi Sad, Vojvodina',
    recapPath: '/recaps/cursor-meetup-novisad-1',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1Z-iGL-XSyStIyD6Y4M2D-w9J4DBsAgK0',
    lumaUrl: 'https://luma.com/3bshmlcv',
    status: 'past',
  },
  {
    id: 'cursor-coworking-nis-1',
    title: 'Cursor Coworking Day in Niš',
    date: '2026-03-20',
    time: '18:00',
    displayDate: 'March 20, 2026',
    attendees: 46,
    location: 'Niš, Serbia',
    recapPath: '/recaps/cursor-coworking-nis-1',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1SspQCSCwKoSE3xmMrI-jxOHywtf8uehF',
    lumaUrl: 'https://luma.com/b9evox5u',
    status: 'past',
  },
  {
    id: 'cursor-coworking-novisad-1',
    title: 'Cursor Coworking Day in Novi Sad',
    date: '2026-03-29',
    time: '10:00',
    displayDate: 'March 29, 2026',
    attendees: 30,
    location: 'Novi Sad, Vojvodina',
    recapPath: '/recaps/cursor-coworking-novisad-1',
    thumbnail: 'https://drive.google.com/uc?export=view&id=1w3sm1HJ0J5ozZEVp9-asQ9wOTKBSKfVI',
    lumaUrl: 'https://luma.com/u5x4q0fl',
    status: 'past',
  },
  {
    id: 'cafe-cursor-novisad-1',
    title: 'Cafe Cursor Novi Sad',
    date: '2026-01-18',
    displayDate: 'January 18, 2026',
    attendees: 46,
    location: 'Novi Sad, Serbia',
    recapPath: '/recaps/cafe-cursor-novisad-1',
    thumbnail: '/images/events/cursorcafe1.jpg',
    lumaUrl: 'https://luma.com/r3pbpvaj',
    status: 'past',
  },
  {
    id: 'cafe-cursor-belgrade-1',
    title: 'Cafe Cursor Belgrade',
    date: '2026-01-25',
    displayDate: 'January 25, 2026',
    attendees: 99,
    location: 'Beldgrade, Serbia',
    recapPath: '/recaps/cafe-cursor-belgrade-1',
    thumbnail: '/images/events/CafeCursorBelgrade12.jpg',
    lumaUrl: 'https://luma.com/tq5s116a',
    status: 'past',
  },
]

export const upcomingEvents = events.filter((event) => event.status === 'upcoming')
export const pastEvents = events
  .filter((event) => event.status === 'past')
  .sort((a, b) => b.date.localeCompare(a.date))
